Adding the Clues component
WildCodeSchool/2023-09-JS-Lille-yellow-project-2-groupe2 pull request #2
Opened 2023-10-25 14:52 UTC by Rayane0823

2023-10-25 15:05 UTC, JulienOza requested changes
folder "Indice" still in French.

2023-10-25 15:09 UTC, JulienOza approved these changes
Code reviewed, Ok.

2023-10-25 15:12 UTC, SebSamPro approved these changes

2023-10-26 07:33 UTC, Yoann-Fortin commented on frontend/src/assets/components/Clues/Clues.css
Why id selector ?

2023-10-26 09:11 UTC, Yoann-Fortin approved these changes

2023-10-26 13:26 UTC, merged